RoR2LogbookMVC/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace RoR2LogbookMVC.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
    }
}

RoR2LogbookMVC/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoR2LogbookMVC.Models;

namespace RoR2LogbookMVC.Controllers
{
    public class ItemsController : Controller
    {
        private readonly RoR2LogbookMVCContext _context;

        public ItemsController(RoR2LogbookMVCContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index(string search, string sort)
        {
            var items = from i in _context.Item
                         select i;

            items = items.OrderBy(s => s.OrderNo);

            ViewData["CurrentFilter"] = search;

            if (sort == "nameDescending")
            {
                items = items.OrderByDescending(s => s.Name);
            }
            else if (sort == "nameAscending")
            {
                items = items.OrderBy(s => s.Name);
            }
            else if (sort == "orderDescending")
            {
                items = items.OrderByDescending(s => s.OrderNo);
            }
            else if (sort == "orderAscending")
            {
                items = items.OrderBy(s => s.OrderNo);
            }

            if (!String.IsNullOrEmpty(search))
            {
                // Select items that contain the search string in their name or description.
                items = items.Where(s => s.Name.Contains(search) || s.Description.Contains(search));
            }

            return View(await items.ToListAsync());
        }

        // GET: Items/Details/{id}
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.ID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Icon,Name,OrderNo,Type,PickupText,Description,Challenge,Notes")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Items/Edit/{id}
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/{id}
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Icon,Name,OrderNo,Type,PickupText,Description,Challenge,Notes")] Item item)
        {
            if (id != item.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Items/Delete/{id}
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.ID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/{id}
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Item.FindAsync(id);
            _context.Item.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any(e => e.ID == id);
        }
    }
}

RoR2LogbookMVC/Controllers/SurvivorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoR2LogbookMVC.Models;

namespace RoR2LogbookMVC.Controllers
{
    public class SurvivorsController : Controller
    {
        private readonly RoR2LogbookMVCContext _context;

        public SurvivorsController(RoR2LogbookMVCContext context)
        {
            _context = context;
        }

        // GET: Survivors
        public async Task<IActionResult> Index(string sort)
        {
            var survivors = from i in _context.Survivor
                        select i;

            survivors = survivors.OrderBy(s => s.OrderNo);

            if (sort == "nameDescending")
            {
                survivors = survivors.OrderByDescending(s => s.Name);
            }
            else if (sort == "nameAscending")
            {
                survivors = survivors.OrderBy(s => s.Name);
            }
            else if (sort == "orderDescending")
            {
                survivors = survivors.OrderByDescending(s => s.OrderNo);
            }
            else if (sort == "orderAscending")
            {
                survivors = survivors.OrderBy(s => s.OrderNo);
            }

            return View(await survivors.ToListAsync());
        }

        // GET: Survivors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survivor = await _context.Survivor
                .FirstOrDefaultAsync(m => m.ID == id);
            if (survivor == null)
            {
                return NotFound();
            }

            return View(survivor);
        }

        // GET: Survivors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Survivors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,OrderNo,Icon,BaseMaxHealth,MaxHealthIncrease,BaseDamage,DamageIncrease,Speed,Challenge,Notes")] Survivor survivor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(survivor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(survivor);
        }

        // GET: Survivors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survivor = await _context.Survivor.FindAsync(id);
            if (survivor == null)
            {
                return NotFound();
            }
            return View(survivor);
        }

        // POST: Survivors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,OrderNo,Icon,BaseMaxHealth,MaxHealthIncrease,BaseDamage,DamageIncrease,Speed,Challenge,Notes")] Survivor survivor)
        {
            if (id != survivor.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(survivor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SurvivorExists(survivor.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(survivor);
        }

        // GET: Survivors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var survivor = await _context.Survivor
                .FirstOrDefaultAsync(m => m.ID == id);
            if (survivor == null)
            {
                return NotFound();
            }

            return View(survivor);
        }

        // POST: Survivors/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var survivor = await _context.Survivor.FindAsync(id);
            _context.Survivor.Remove(survivor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SurvivorExists(int id)
        {
            return _context.Survivor.Any(e => e.ID == id);
        }
    }
}

RoR2LogbookMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Risk of Rain 2 Logbook</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Items" asp-action="Index">Risk of Rain 2 Logbook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Items" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Survivors" asp-action="Index">Survivors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

        <div class="container" style="background-color: rgba(50, 50, 50, 0.8); border-radius: 10px; padding-top: 10px;">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


    <footer class="footer border-top bg-dark text-light">
        <div class="container">
            &copy; 2019 - Daniel Bedggood
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>